polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
'''urlpatterns = [
	# ex: /polls/
    path('', views.index, name='index'),
    # ex: /polls/5/
    path('<int:question_id>/', views.detail, name='detail'),
    # ex: /polls/5/results/
    path('<int:question_id>/results/', views.results, name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]'''
urlpatterns = [
 	path('', views.IndexView.as_view(), name='index'),
 	path('<int:pk>/', views.DetailView.as_view(), name='detail'),
 	path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
 	path('<int:question_id>/vote/', views.vote, name='vote')
 ]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
	question_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')

	def __str__(self):
		return self.question_text

	def was_published_recently(self):
		now = timezone.now()
		return now - datetime.timedelta(days=1) <= self.pub_date <= now
	#to improve the name of the method in the admin page
	was_published_recently.admin_order_field = 'pub_date'
	was_published_recently.boolean = True
	was_published_recently.short_description = 'Publshed recently?'

class Choice(models.Model):
	question = models.ForeignKey(Question, on_delete = models.CASCADE)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)

	def __str__(self):
		return self.choice_text   

class Hint(models.Model):
	question = models.ForeignKey(Question, on_delete = models.CASCADE)
	hint_text = models.TextField(max_length=200)

	def __str__(self):
		return self.hint_text
		

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
#from django.http import Http404

from .models import Question, Choice

# Create your views here.
'''def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list,}
    return render(request, 'polls/index.html', context)

def detail(request, question_id):
	"""try:
		question = Question.objects.get(pk=question_id)
	except Question.DoesNotExist:
		raise Http404("Question does not Exist")
	return render(request, 'polls/detail.html', {'question': question})"""
	question = get_object_or_404(Question, pk=question_id)
	return render(request, 'polls/detail.html', {'question': question})

def results(request, question_id):
	question = get_object_or_404(Question, pk=question_id)
	return render(request, 'polls/results.html', {'question':question})'''

'''ListView and DetailView abstract the concept of "display a list of objects" and "display a detail page for a particular type of object".'''
from django.utils import timezone

class IndexView(generic.ListView):
	template_name = 'polls/index.html'
	context_object_name = 'latest_question_list'

	def get_queryset(self):
		'''Return the last five published questions.'''
		#return Question.objects.order_by('-pub_date')[:5]
		#Question.objects.filter(pub_date__lte=timezone.now()) returns a queryset containing Questions whose pub_date is less than or equal to- that is earlier than or equal to- timezone.now
		q = Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')
		return q

class DetailView(generic.DetailView):
	model = Question
	template_name = 'polls/detail.html'

	def get_query(self):
		"""
		Excludes any questions that arent published yet.
		"""
		return Question.objects.filter(pub_date__lte=timezone.now())
	
class ResultsView(generic.DetailView):
	model = Question
	template_name = 'polls/results.html'	

def vote(request, question_id):
	question = get_object_or_404(Question, pk=question_id)
	try:
		selected_choice = question.choice_set.get(pk=request.POST['choice'])
	except (KeyError, Choice.DoesNotExist):
		#Redisplay the question voting form.
		return render(request, 'polls/detail.html', {'question':question, 'error_message':"You didn't select a choice"})
	else:
		selected_choice.votes += 1
		selected_choice.save()
		#Always return an HttpResponseRedirect after successfully dealing with POST data. This prevents data from being posted twice if a user hits the Back button.
		return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

polls/templates/polls/detail.html
<h1>{{ question.question_text }} </h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
	{% csrf_token %}
	{% for choice in question.choice_set.all %}
		<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}"><label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
	{% endfor %}

	{% if question.hint_set.all %}
		<strong><u>Hint</u></strong>
		<ul>
			{% for hint in question.hint_set.all %}
				<li>{{hint.hint_text}}</li> 
			{% endfor %}
		</ul>
	{% endif %}

	<input type="submit" value="vote" >
</form>

polls/templates/polls/index.html
<!DOCTYPE html>
<html>
<head>
	<title>Polls</title>
	{% load static %}
	<link rel="stylesheet", type="text/css" href="{% static 'polls/style.css' %}">
</head>
</head>
<body>
	{% if latest_question_list %}
    <ul>
    	{% for question in latest_question_list %}
        	<li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    	{% endfor %}
    </ul>
	{% else %}
    	<p>No polls are available.</p>
	{% endif %}
</body>
</html>
<head> 

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
	{% for choice in question.choice_set.all %}
		<li>{{ choice.choice_text}} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
	{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>